name: CI Pipeline for MyPy and Ruff

on:
  # Trigger the workflow on pull requests and pushes to the main branch
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi


     # Run Ruff for linting and formatting checks
      - name: Run Ruff
        run: |
          poetry run ruff format --check  
          poetry run ruff check
          
        continue-on-error: false  # Fail the pipeline if there are issues
      - name: Run MyPy
        run: |
          poetry run mypy .
        
        continue-on-error: false  # Fail the pipeline if there are issues

