repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.7
    hooks:
      # Run the linter.
      - id: ruff
        args:
          - --fix  # Optional: to automatically fix linting errors
          - --line-length=88  # Align with Black's line length
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Replace with the latest version if needed
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports  # Prevents errors from external imports
          - --strict  # Optional: adds strict type checking
